version: "3.0"
services:
  depoly_test:
    image: micro-service-utc:0.0.1
    container_name: depoly_test
    hostname: depoly_test
    build:
      context: ./docker
      dockerfile: Dockerfile
    user: root
    restart: always
    volumes:
      - "/home/ubuntu/ServiceLogs/depoly_test/log/:/var/www/html/microService/log/"
      - "/home/ubuntu/ServiceLogs/depoly_test/supervisor/:/var/log/supervisor"
      - "/home/ubuntu/depoly_test:/var/www/html/microService"
    ports:
      - "3030:3030"
    networks:
      - net

networks:
    net:
      external: true